### ISSUE TITLE
导航标题重叠

### ISSUE THREAD

**Issue by 394988736** [masastack/MASA.Blazor.Pro#191]
### Description

![K5S3$VX)NLN2%~)WO$6C)XU](https://github.com/masastack/MASA.Blazor.Pro/assets/81234257/9b2c8392-905b-4576-b1ba-b2d8f9363e7c)
这种重叠的情况是考虑过，合理存在的吗？

**Comment by capdiem** [comment]
@394988736 背景是透明的，你可以给面包屑设置跟应用一样的底色：
```css
.default-app-bar__nav {
  ...
  background-color: #f0f3fa;
}
```
